import { create } from "zustand";

interface CountryState {
    country: string;
    list: string[];
    keys: Record<string, string>;
    setCountry: (country: string) => void;
}

export const countryStore = create<CountryState>((set) => ({
    country: "Indonesian (Indonesia)",
    list: [
        "Afrikaans (South Africa)",
        "Arabic",
        "Azerbaijani",
        "Base",
        "Czech (Czechia)",
        "Danish",
        "German",
        "German (Austria)",
        "German (Switzerland)",
        "Maldivian",
        "Greek",
        "English",
        "English (Australia)",
        "English (Australia Ocker)",
        "English (Bork)",
        "English (Canada)",
        "English (Great Britain)",
        "English (Ghana)",
        "English (Hong Kong)",
        "English (Ireland)",
        "English (India)",
        "English (Nigeria)",
        "English (United States)",
        "English (South Africa)",
        "Esperanto",
        "Spanish",
        "Spanish (Mexico)",
        "Farsi/Persian",
        "Finnish",
        "French",
        "French (Belgium)",
        "French (Canada)",
        "French (Switzerland)",
        "French (Luxembourg)",
        "French (Senegal)",
        "Hebrew",
        "Croatian",
        "Hungarian",
        "Armenian",
        "Indonesian (Indonesia)",
        "Italian",
        "Japanese",
        "Georgian (Georgia)",
        "Korean",
        "Latvian",
        "Macedonian",
        "Norwegian (Norway)",
        "Nepali",
        "Dutch",
        "Dutch (Belgium)",
        "Polish",
        "Portuguese (Brazil)",
        "Portuguese (Portugal)",
        "Romanian",
        "Romanian (Moldova)",
        "Russian",
        "Slovak",
        "Serbian (Serbia, Latin)",
        "Swedish",
        "Thai",
        "Turkish",
        "Ukrainian",
        "Urdu",
        "Vietnamese",
        "Yoruba (Nigeria)",
        "Chinese (China)",
        "Chinese (Taiwan)",
        "Zulu (South Africa)",
    ],
    keys: {
        af_ZA: "Afrikaans (South Africa)",
        ar: "Arabic",
        az: "Azerbaijani",
        base: "Base",
        cs_CZ: "Czech (Czechia)",
        da: "Danish",
        de: "German",
        de_AT: "German (Austria)",
        de_CH: "German (Switzerland)",
        dv: "Maldivian",
        el: "Greek",
        en: "English",
        en_AU: "English (Australia)",
        en_AU_ocker: "English (Australia Ocker)",
        en_BORK: "English (Bork)",
        en_CA: "English (Canada)",
        en_GB: "English (Great Britain)",
        en_GH: "English (Ghana)",
        en_HK: "English (Hong Kong)",
        en_IE: "English (Ireland)",
        en_IN: "English (India)",
        en_NG: "English (Nigeria)",
        en_US: "English (United States)",
        en_ZA: "English (South Africa)",
        eo: "Esperanto",
        es: "Spanish",
        es_MX: "Spanish (Mexico)",
        fa: "Farsi/Persian",
        fi: "Finnish",
        fr: "French",
        fr_BE: "French (Belgium)",
        fr_CA: "French (Canada)",
        fr_CH: "French (Switzerland)",
        fr_LU: "French (Luxembourg)",
        fr_SN: "French (Senegal)",
        he: "Hebrew",
        hr: "Croatian",
        hu: "Hungarian",
        hy: "Armenian",
        id_ID: "Indonesian (Indonesia)",
        it: "Italian",
        ja: "Japanese",
        ka_GE: "Georgian (Georgia)",
        ko: "Korean",
        lv: "Latvian",
        mk: "Macedonian",
        nb_NO: "Norwegian (Norway)",
        ne: "Nepali",
        nl: "Dutch",
        nl_BE: "Dutch (Belgium)",
        pl: "Polish",
        pt_BR: "Portuguese (Brazil)",
        pt_PT: "Portuguese (Portugal)",
        ro: "Romanian",
        ro_MD: "Romanian (Moldova)",
        ru: "Russian",
        sk: "Slovak",
        sr_RS_latin: "Serbian (Serbia, Latin)",
        sv: "Swedish",
        th: "Thai",
        tr: "Turkish",
        uk: "Ukrainian",
        ur: "Urdu",
        vi: "Vietnamese",
        yo_NG: "Yoruba (Nigeria)",
        zh_CN: "Chinese (China)",
        zh_TW: "Chinese (Taiwan)",
        zu_ZA: "Zulu (South Africa)",
    },
    setCountry: (country) => set({ country }),
}));
